name: ZeroTier VPC Workflow

on:
    push:
        branches: main
    workflow_dispatch:

jobs:
    zerotier:
        runs-on: ubuntu-latest
        steps:
            - name: Install ZeroTier install
              run: curl -s https://install.zerotier.com | sudo bash
            - name: Join ZeroTier Network
              run: sudo zerotier-cli join ${{ secrets.ZEROTIER_NETWORKID }}
            - name: Authorize ZeroTier Client
              shell: pwsh
              run: |
                  $result = sudo zerotier-cli info
                  $result[0] -match '\w{10}'
                  $ClientId = $matches[0]
                  $Uri = 'https://my.zerotier.com/api/v1/network/${{ secrets.ZEROTIER_NETWORKID }}/member/{0}' -f $ClientId
                  $Token = ConvertTo-SecureString -AsPlainText -Force -String ${{ secrets.ZEROTIER_APIKEY }}
                  Invoke-RestMethod -Uri $Uri -Method Post -Authentication Bearer -Token $Token
